require 'yaml'


task :default => [:helper]

task :helper do
	`sass --scss --style compact src\\deputy.scss dist\\deputy.css`
	`sass --scss --style compressed src\\deputy.scss dist\\deputy.min.css`

	license = "/* 
*
*      ___           ___           ___           ___           ___           ___                    ___           ___           ___     
*     /\\  \\         /\\  \\         /\\  \\         /\\__\\         /\\  \\         |\\__\\                  /\\  \\         /\\  \\         /\\  \\    
*    /##\\  \\       /##\\  \\       /##\\  \\       /#/  /         \\#\\  \\        |#|  |                /##\\  \\       /##\\  \\       /##\\  \\   
*   /#/\\#\\  \\     /#/\\#\\  \\     /#/\\#\\  \\     /#/  /           \\#\\  \\       |#|  |               /#/\\#\\  \\     /#/\\ \\  \\     /#/\\ \\  \\  
*  /#/  \\#\\__\\   /##\\~\\#\\  \\   /##\\~\\#\\  \\   /#/  /  ___       /##\\  \\      |#|__|__            /#/  \\#\\  \\   _\\#\\~\\ \\  \\   _\\#\\~\\ \\  \\ 
* /#/__/ \\#|__| /#/\\#\\ \\#\\__\\ /#/\\#\\ \\#\\__\\ /#/__/  /\\__\\     /#/\\#\\__\\     /####\\__\\          /#/__/ \\#\\__\\ /\\ \\#\\ \\ \\__\\ /\\ \\#\\ \\ \\__\\
* \\#\\  \\ /#/  / \\#\\~\\#\\ \\/__/ \\/__\\#\\/#/  / \\#\\  \\ /#/  /    /#/  \\/__/    /#/~~/~             \\#\\  \\  \\/__/ \\#\\ \\#\\ \\/__/ \\#\\ \\#\\ \\/__/
*  \\#\\  /#/  /   \\#\\ \\#\\__\\        \\##/  /   \\#\\  /#/  /    /#/  /        /#/  /                \\#\\  \\        \\#\\ \\#\\__\\    \\#\\ \\#\\__\\  
*   \\#\\/#/  /     \\#\\ \\/__/         \\/__/     \\#\\/#/  /     \\/__/         \\/__/                  \\#\\  \\        \\#\\/#/  /     \\#\\/#/  /  
*    \\##/__/       \\#\\__\\                      \\##/  /                                            \\#\\__\\        \\##/  /       \\##/  /   
*     ~~            \\/__/                       \\/__/                                              \\/__/         \\/__/         \\/__/    
*
* Deputy Css v0.1
*
* Copyright © 2013 Ryan Olson <ryan@americommerce.com>
* This work is free. You can redistribute it and/or modify it under the
* terms of the Do What The Fuck You Want To Public License, Version 2,
* as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
*
* https://github.com/ry4nolson/Deputy
*/\n\n"


	file = File.read('dist\\deputy.css')
	file = file.gsub(/\n\n/, "\n")
	file = file.gsub(/\/\* \*\//, "")
	file = license + file

	file2 = File.read('dist\\deputy.min.css')
	file2 = license + file2

	File.open('dist\\deputy.css', 'w') do |f|
		f.puts file
	end

	File.open('dist\\deputy.min.css', 'w') do |f|
		f.puts file2
	end
	
	puts 'Build complete'
end
